language: c++

cache: apt

dist: trusty

sudo: required

os:
  - linux
  - osx

compiler:
  - gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update;
      sudo apt-get install -qq build-essential xorg-dev libglu1-mesa-dev libglew-dev libglm-dev;
      sudo apt-get install -qq cmake;

      wget https://github.com/glfw/glfw/releases/download/3.1.1/glfw-3.1.1.zip;
      unzip glfw-3.1.1.zip;
      cd glfw-3.1.1;
      sudo cmake -G "Unix Makefiles" -DBUILD_SHARED_LIBS=ON;
      sudo make;
      sudo make install;
      cmake --version;
      cd ..;

      travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.8.tar.gz | tar xz;
      cd SDL2-2.0.8;
      ./configure;
      make;
      sudo make install;
      cd ..;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glfw; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install fftw; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      echo "Install ...";
    fi

script:
  - make

addons:
  apt:
    packages:
      - libfftw3-dev
